spring:
    application:
        name: "stash-o"
    datasource:
        driver-class-name: "org.postgresql.Driver"
        url: jdbc:postgresql://localhost:1440/postgres
        username: postgres
        password: sto_2021*po-1
    devtools:
        restart:
            quiet-period: 900
    server:
        port: 5432