spring:
    application:
        name: "stash-o"
    datasource:
        driver-class-name: org.postgresql.Driver
        url: "jdbc:postgresql://localhost:1440/postgres"
        username: postgres
        password: sto_2021*po-1
    devtools:
        restart:
            quiet-period: 900
    thymeleaf:
        cache: false
        mode: HTML
        encoding: UTF-8
        prefix: file:src/main/resources/templates/